2023-03-14 16:11:53,777 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . 
2023-03-14 16:12:00,804 INFO server.py Установлено соедение с ПК ('127.0.0.1', 34369)
2023-03-14 16:12:00,804 DEBUG server.py Получено сообщение {'action': 'authenticate', 'time': 1678799520.8041425, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:12:00,804 INFO server.py Cформирован ответ клиенту {'response': 200, 'alert': 'OK'}
2023-03-14 16:12:00,805 DEBUG server.py Соединение с клиентом ('127.0.0.1', 34369) закрывается.
2023-03-14 16:25:44,597 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . 
2023-03-14 16:25:48,585 INFO server.py Установлено соедение с ПК ('127.0.0.1', 56230)
2023-03-14 16:25:48,586 DEBUG server.py Получено сообщение {'action': 'authenticate', 'time': 1678800348.5852165, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:25:48,586 INFO server.py Cформирован ответ клиенту {'response': 200, 'alert': 'OK'}
2023-03-14 16:25:48,586 DEBUG server.py Соединение с клиентом ('127.0.0.1', 56230) закрыто.
2023-03-14 16:26:10,385 INFO server.py Установлено соедение с ПК ('127.0.0.1', 56239)
2023-03-14 16:26:10,387 ERROR server.py Не удалось декодировать JSON строку, полученную от клиента ('127.0.0.1', 56239). Соединение закрывается.
2023-03-14 16:26:34,180 INFO server.py Установлено соедение с ПК ('127.0.0.1', 56249)
2023-03-14 16:26:34,182 ERROR server.py Не удалось декодировать JSON строку, полученную от клиента ('127.0.0.1', 56249). Соединение закрывается.
2023-03-14 16:26:48,882 INFO server.py Установлено соедение с ПК ('127.0.0.1', 56267)
2023-03-14 16:26:48,883 DEBUG server.py Получено сообщение {'action': 'authenticate', 'time': 1678800408.8828897, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:26:48,883 INFO server.py Cформирован ответ клиенту {'response': 200, 'alert': 'OK'}
2023-03-14 16:26:48,883 DEBUG server.py Соединение с клиентом ('127.0.0.1', 56267) закрыто.
2023-03-14 16:29:26,528 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . 
2023-03-14 16:29:32,229 INFO server.py Установлено соедение с ПК ('127.0.0.1', 56357)
2023-03-14 16:29:32,229 DEBUG server.py Получено сообщение {'action': 'authenticate', 'time': 1678800572.2284405, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:29:32,229 DEBUG server.py Разбор сообщения от клиента : {'action': 'authenticate', 'time': 1678800572.2284405, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:29:32,229 INFO server.py Cформирован ответ клиенту {'response': 200, 'alert': 'OK'}
2023-03-14 16:29:32,229 DEBUG server.py Соединение с клиентом ('127.0.0.1', 56357) закрыто.
2023-03-14 16:39:03,261 INFO server.py Установлено соедение с ПК ('127.0.0.1', 56624)
2023-03-14 16:39:03,261 DEBUG server.py Получено сообщение {'action': 'authenticate', 'time': 1678801143.2611995, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:39:03,261 DEBUG server.py Разбор сообщения от клиента : {'action': 'authenticate', 'time': 1678801143.2611995, 'user': {'account_name': 'User1', 'password': 'Password123'}}
2023-03-14 16:39:03,261 INFO server.py Cформирован ответ клиенту {'response': 200, 'alert': 'OK'}
2023-03-14 16:39:03,262 DEBUG server.py Соединение с клиентом ('127.0.0.1', 56624) закрыто.
